### ISSUE TITLE
Allow same MAC addresses in different networks

### ISSUE THREAD

**Issue by sebschrader** [agdsn/hades#92]
Currently duplicate MAC addresses for `dhcphost` are rejected:

https://github.com/agdsn/hades/blob/8fb471c485251c02856d7f81a6bc2562842af2ca/templates/schema.sql.j2#L283

It seems, that dnsmasq is fine with duplicate MAC addresses, as long as they are in different subnets:

https://github.com/dnsmasq/dnsmasq/blob/ce5732e84fc46d7f99c152f736cfb4ef5ec98a01/src/dhcp-common.c#L292

If that's the case, we should allow that, because duplicate MAC addresses can happen, if users move.

**Comment by sebschrader** [comment]
Fixed in 2ec2219db66ffcd2073e108c5aba5797c751ce1a

**Comment by lukasjuhrich** [comment]
Not quite fixed: https://github.com/agdsn/hades/blob/2ec2219db66ffcd2073e108c5aba5797c751ce1a/templates/schema.sql.j2#L792-L796

This index still prevents multiple MAC addresses.
